/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from "three";

export default function Hoodie({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Hoodie.glb')
  const imgLink = "https://images.unsplash.com/photo-1447433589675-4aaa569f3e05?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80"
  const imgTexture = useTexture(imgLink);
  imgTexture.wrapS = THREE.RepeatWrapping;
  imgTexture.repeat.x = - 1;

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.test005.geometry} material={materials['lambert1.001']} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} material-color= "#000000" />
      <mesh geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} position={[0, 0.4, 0.12]} rotation={[-Math.PI / 2, 0, Math.PI]} material-map={imgTexture}/>
    </group>
  )
}

useGLTF.preload('/Hoodie.glb')
